# ================================================================
# PATHFINITY KUBERNETES NAMESPACE
# Production namespace with resource quotas and security policies
# ================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: pathfinity-production
  labels:
    app: pathfinity
    environment: production
    version: "1.0.0"
  annotations:
    description: "Pathfinity AI Education Platform - Production Environment"

---
# ================================================================
# RESOURCE QUOTA
# ================================================================

apiVersion: v1
kind: ResourceQuota
metadata:
  name: pathfinity-quota
  namespace: pathfinity-production
spec:
  hard:
    # Compute resources
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    
    # Storage
    requests.storage: 500Gi
    persistentvolumeclaims: "20"
    
    # Objects
    pods: "50"
    services: "20"
    secrets: "30"
    configmaps: "30"
    
    # Load balancers
    services.loadbalancers: "3"

---
# ================================================================
# LIMIT RANGE
# ================================================================

apiVersion: v1
kind: LimitRange
metadata:
  name: pathfinity-limits
  namespace: pathfinity-production
spec:
  limits:
    # Container limits
    - type: Container
      default:
        cpu: 500m
        memory: 1Gi
      defaultRequest:
        cpu: 100m
        memory: 256Mi
      max:
        cpu: "2"
        memory: 4Gi
      min:
        cpu: 50m
        memory: 128Mi
    
    # Pod limits
    - type: Pod
      max:
        cpu: "4"
        memory: 8Gi
      min:
        cpu: 100m
        memory: 256Mi
    
    # PVC limits
    - type: PersistentVolumeClaim
      max:
        storage: 100Gi
      min:
        storage: 1Gi

---
# ================================================================
# NETWORK POLICY
# ================================================================

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pathfinity-network-policy
  namespace: pathfinity-production
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  
  ingress:
    # Allow ingress from nginx ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
    
    # Allow ingress within namespace
    - from:
        - namespaceSelector:
            matchLabels:
              name: pathfinity-production
    
    # Allow monitoring from prometheus
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 9090
  
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    
    # Allow HTTPS to external services
    - to: []
      ports:
        - protocol: TCP
          port: 443
    
    # Allow database connections
    - to:
        - namespaceSelector:
            matchLabels:
              name: pathfinity-production
      ports:
        - protocol: TCP
          port: 5432
    
    # Allow Redis connections
    - to:
        - namespaceSelector:
            matchLabels:
              name: pathfinity-production
      ports:
        - protocol: TCP
          port: 6379